source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "Algebra"
    task = "Exam prep"
  }
  client_id                         = "f5b6a5cf-fbdf-4a9f-b3b8-3c2cd00225a4"
  client_secret                     = "0e760437-bf34-4aad-9f8d-870be799c55d"
  image_offer                       = "0001-com-ubuntu-server-jammy"
  image_publisher                   = "canonical"
  image_sku                         = "22_04-lts"
  location                          = "East US"
  managed_image_name                = "UbuntuExamImage"
  managed_image_resource_group_name = "Exam-prep"
  os_type                           = "Linux"
  subscription_id                   = "256acc46-4404-4fe1-8a11-d55efd4b6faa"
  tenant_id                         = "d974b4df-eec2-433e-a918-3fe18412735f"
  vm_size                           = "Standard_DS2_v2"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    inline = ["apt-get update", "apt-get upgrade -y", "apt-get -y install nginx", "systemctl enable nginx", "systemctl start nginx", "echo "PACKER INSIDE A CONTAINER WOOOOO" > /var/www/html/index.nginx-debian.html", "chown www-data:www-data /var/www/html/index.nginx-debian.html"]
  }

}
